"""llm_calls cached flag

Revision ID: 717b7b52ed7d
Revises: 8f1dc7ea4b67
Create Date: 2026-10-04 01:13:01.427176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate references pgvector types without importing them; every
# migration needs this or it fails with NameError at upgrade time.
import pgvector.sqlalchemy  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '717b7b52ed7d'
down_revision: Union[str, Sequence[str], None] = '8f1dc7ea4b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_calls', sa.Column('cached', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_calls', 'cached')
    # ### end Alembic commands ###
