"""users and ownership

Revision ID: a1c4e9b2d701
Revises: 98a232f2483b
Create Date: 2026-10-04 12:10:00.000000

Written by hand rather than autogenerated: the ordering is the point. The new columns go
on nullable, existing rows are given an owner, and only then does `analyses.user_id`
become NOT NULL. Autogenerate emits the constraint first, which fails on any database
that already holds analyses.

Existing data sources are deliberately left with `owner_id IS NULL` — that is the "shared
source" state, which is exactly right for the seeded demo database.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# Autogenerate references pgvector types without importing them; every
# migration needs this or it fails with NameError at upgrade time.
import pgvector.sqlalchemy  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'a1c4e9b2d701'
down_revision: Union[str, Sequence[str], None] = '98a232f2483b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(as_uuid=True), nullable=True),
        sa.Column("user_agent", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"], ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_refresh_tokens"), ondelete="SET NULL",
        ),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"])
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )

    op.add_column("analyses", sa.Column("user_id", sa.UUID(as_uuid=True), nullable=True))
    op.add_column("llm_calls", sa.Column("user_id", sa.UUID(as_uuid=True), nullable=True))
    op.add_column("data_sources", sa.Column("owner_id", sa.UUID(as_uuid=True), nullable=True))

    # Give any pre-auth analyses an owner so the NOT NULL below can be applied. The
    # placeholder hash is unusable by design: this account cannot be logged into until
    # someone sets a real password on it.
    conn = op.get_bind()
    orphans = conn.execute(sa.text("SELECT count(*) FROM analyses")).scalar_one()
    if orphans:
        conn.execute(
            sa.text(
                "INSERT INTO users (id, email, hashed_password, full_name, is_admin) "
                "VALUES (gen_random_uuid(), :email, '!', 'Legacy owner', true) "
                "ON CONFLICT (email) DO NOTHING"
            ),
            {"email": "legacy@insightflow.local"},
        )
        conn.execute(
            sa.text(
                "UPDATE analyses SET user_id = "
                "(SELECT id FROM users WHERE email = :email) WHERE user_id IS NULL"
            ),
            {"email": "legacy@insightflow.local"},
        )
        conn.execute(
            sa.text(
                "UPDATE llm_calls SET user_id = a.user_id FROM analyses a "
                "WHERE llm_calls.analysis_id = a.id AND llm_calls.user_id IS NULL"
            )
        )

    op.alter_column("analyses", "user_id", nullable=False)

    op.create_foreign_key(
        op.f("fk_analyses_user_id_users"), "analyses", "users", ["user_id"], ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_llm_calls_user_id_users"), "llm_calls", "users", ["user_id"], ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_data_sources_owner_id_users"), "data_sources", "users", ["owner_id"], ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_analyses_user_created", "analyses", ["user_id", "created_at"])
    op.create_index("ix_llm_calls_user_created", "llm_calls", ["user_id", "created_at"])
    op.create_index(op.f("ix_data_sources_owner_id"), "data_sources", ["owner_id"])


def downgrade() -> None:
    op.drop_index(op.f("ix_data_sources_owner_id"), table_name="data_sources")
    op.drop_index("ix_llm_calls_user_created", table_name="llm_calls")
    op.drop_index("ix_analyses_user_created", table_name="analyses")
    op.drop_constraint(op.f("fk_data_sources_owner_id_users"), "data_sources", type_="foreignkey")
    op.drop_constraint(op.f("fk_llm_calls_user_id_users"), "llm_calls", type_="foreignkey")
    op.drop_constraint(op.f("fk_analyses_user_id_users"), "analyses", type_="foreignkey")
    op.drop_column("data_sources", "owner_id")
    op.drop_column("llm_calls", "user_id")
    op.drop_column("analyses", "user_id")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
